remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Ben Emanuel â€“ Cybersecurity Student
description: Cybersecurity & Data Analytics student at VT. GitHub projects, labs, and resume.
logo: /banner.png
