remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Ben J. Emanuel
description: Cybersecurity & Data Analytics student at Virginia Tech. 2026 NCAE Cyber Games Competitor.
image: /banner.png
