remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Ben J. Emanuel | Cybersecurity Portfolio
description: "Cybersecurity & Data Analytics student at Virginia Tech. 2026 NCAE Cyber Games Competitor. Explore my Python security tools, ISC2 CC certification, and technical projects."
author: Ben J. Emanuel
image: /banner.png
Published: 01/31/2026
